export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE';
export const START_FETCHING_CHARACTERS = 'START_FETCHING_CHARACTERS';
export const STOP_FETCHING_CHARACTERS = 'STOP_FETCHING_CHARACTERS';
//user
export const PERFORM_LOGIN = 'PERFORM_LOGIN';
export const USER_LOADING = 'USER_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const PERFORM_LOGON = 'PERFORM_LOGON';
export const LOGON_SUCCESS = 'LOGON_SUCCESS';
export const LOGON_FAILURE = 'LOGON_FAILURE';
//notification
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';
//channel
export const CHANNEL_LOADING = 'CHANNEL_LOADING';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';
export const UPDATE_LAST_MESSAGE = 'UPDATE_LAST_MESSAGE';
//room
export const ROOM_INFO_LOADING = 'ROOM_INFO_LOADING';
export const ROOM_MESSAGES_LOADING = 'ROOM_MESSAGES_LOADING';
export const FETCH_ROOM_INFO_SUCCESS = 'FETCH_ROOM_INFO_SUCCESS';
export const FETCH_ROOM_INFO_FAILURE = 'FETCH_ROOM_INFO_FAILURE';
export const FETCH_ROOM_MESSAGES_SUCCESS = 'FETCH_ROOM_MESSAGES_SUCCESS';
export const FETCH_ROOM_MESSAGES_FAILURE = 'FETCH_ROOM_MESSAGES_FAILURE';
export const PUSH_MESSAGE = 'PUSH_MESSAGE';
